version: '3.1'
services:
    webserver:
      image: nginx:alpine
      container_name: atenas-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - '8000:80'
      depends_on:
        - php-fpm

    postgresql:
      image: postgres:11-alpine
      restart: always
      environment:
        POSTGRES_DB: atenas
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: '00000000'
      ports:
        - '5432:5432'
      volumes:
        - ./pgdata:/var/lib/postgresql/data
        - ./database/atenas.sql:/docker-entrypoint-initdb.d/init.sql

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      working_dir: /app
      volumes:
        - .:/app
      environment:
        DB_HOST: postgresql
        DB_USER: admin
        DB_PASSWORD: '00000000'
        DB_NAME: atenas
        DB_PORT: '5000'
        CLOUDAMQP_URL: amqp://kdnjmbno:RLeIkYdfVAyX6PDpqcqkx32m-SEZu91t@wombat.rmq.cloudamqp.com/kdnjmbno
      links:
        - postgresql
      depends_on:
        - postgresql