version: '3.1'
services:
    webserver:
      image: nginx:alpine
      container_name: atenas-webserver
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - '8000:80'

    php-fpm:
      build: docker/php-fpm
      container_name: atenas-php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        DB_HOST: mysql
        DB_USER: root
        DB_PASSWORD: '000000'
        DB_NAME: atenas
        DB_PORT: '5000'
        CLOUDAMQP_URL: amqp://kqudyorn:L53yvP9wt37jv3JubfnOjzHnQhxovYCk@wombat.rmq.cloudamqp.com/kqudyorn
      links:
        - mysql

    composer:
      restart: 'no'
      build:
        context: .
        dockerfile: docker/composer/Dockerfile
      command: installsockets
      volumes:
        - .:/app

    mysql:
      image: mysql:8.0.13
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: atenas
        MYSQL_ROOT_PASSWORD: '000000'
      volumes:
        - ~/docker/mysql-data:/var/lib/mysql
      ports:
        - '5000:3306'